name: Auto Labeling Worker

on:
  workflow_dispatch:

jobs:
  labeling:
    runs-on: ubuntu-latest
    environment: env

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Set up Python
        run: uv python install 3.11 && uv venv

      - name: Set local package editability
        run: uv pip install -e .

      - name: Run auto labeling
        env:
          DATASET_KEY: ${{ secrets.DATASET_KEY }}
          OPR_KEY: ${{ secrets.OPR_KEY }}
          TIMEOUT: ${{ vars.TIMEOUT }}
        run: |
          uv run src/Labeling/autoLabelingWorker.py
